// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :exec
UPDATE oauth_authorization_codes
SET consumed_at = now()
WHERE code = $1
`

func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, consumeAuthorizationCode, code)
	return err
}

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO auth_email_tokens (user_id, token_hash, token_type, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateEmailTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	TokenType string    `json:"token_type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.ExecContext(ctx, createEmailToken,
		arg.UserID,
		arg.TokenHash,
		arg.TokenType,
		arg.ExpiresAt,
	)
	return err
}

const createMFAPending = `-- name: CreateMFAPending :exec
INSERT INTO auth_mfa_pending (id, user_id, client_id, redirect_uri, state, scope, code_challenge, code_challenge_method, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateMFAPendingParams struct {
	ID                  string         `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	ClientID            sql.NullString `json:"client_id"`
	RedirectUri         sql.NullString `json:"redirect_uri"`
	State               sql.NullString `json:"state"`
	Scope               []string       `json:"scope"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	ExpiresAt           time.Time      `json:"expires_at"`
}

func (q *Queries) CreateMFAPending(ctx context.Context, arg CreateMFAPendingParams) error {
	_, err := q.db.ExecContext(ctx, createMFAPending,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.RedirectUri,
		arg.State,
		pq.Array(arg.Scope),
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (
  client_id,
  client_secret,
  name,
  redirect_uris,
  allowed_scopes,
  is_confidential,
  audience
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, client_secret, name, redirect_uris, allowed_scopes, is_confidential, audience, created_at, updated_at
`

type CreateOAuthClientParams struct {
	ClientID       string         `json:"client_id"`
	ClientSecret   sql.NullString `json:"client_secret"`
	Name           string         `json:"name"`
	RedirectUris   []string       `json:"redirect_uris"`
	AllowedScopes  []string       `json:"allowed_scopes"`
	IsConfidential bool           `json:"is_confidential"`
	Audience       string         `json:"audience"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, createOAuthClient,
		arg.ClientID,
		arg.ClientSecret,
		arg.Name,
		pq.Array(arg.RedirectUris),
		pq.Array(arg.AllowedScopes),
		arg.IsConfidential,
		arg.Audience,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.AllowedScopes),
		&i.IsConfidential,
		&i.Audience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec

INSERT INTO auth_email_tokens (user_id, token_hash, token_type, expires_at)
VALUES ($1, $2, 'password_reset', $3)
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Password reset token queries (using auth_email_tokens table)
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth_users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, email, is_active, created_at, updated_at, mfa_enabled, mfa_secret, mfa_verified_at, email_verified, email_verified_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaVerifiedAt,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE auth_users
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, id)
	return err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :exec
DELETE FROM auth_email_tokens WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEmailTokens)
	return err
}

const deleteExpiredMFAPending = `-- name: DeleteExpiredMFAPending :exec
DELETE FROM auth_mfa_pending WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredMFAPending(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMFAPending)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM auth_email_tokens
WHERE token_type = 'password_reset'
  AND (expires_at <= now() OR used_at IS NOT NULL)
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteMFAPending = `-- name: DeleteMFAPending :exec
DELETE FROM auth_mfa_pending WHERE id = $1
`

func (q *Queries) DeleteMFAPending(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMFAPending, id)
	return err
}

const deleteOAuthClient = `-- name: DeleteOAuthClient :exec
DELETE FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) DeleteOAuthClient(ctx context.Context, clientID string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthClient, clientID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserEmailTokens = `-- name: DeleteUserEmailTokens :exec
DELETE FROM auth_email_tokens WHERE user_id = $1 AND token_type = $2
`

type DeleteUserEmailTokensParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenType string    `json:"token_type"`
}

func (q *Queries) DeleteUserEmailTokens(ctx context.Context, arg DeleteUserEmailTokensParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserEmailTokens, arg.UserID, arg.TokenType)
	return err
}

const disableMFA = `-- name: DisableMFA :exec
UPDATE auth_users
SET mfa_enabled = false, mfa_secret = NULL, mfa_verified_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) DisableMFA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, disableMFA, id)
	return err
}

const enableMFA = `-- name: EnableMFA :exec
UPDATE auth_users
SET mfa_enabled = true, mfa_secret = $2, mfa_verified_at = now(), updated_at = now()
WHERE id = $1
`

type EnableMFAParams struct {
	ID        uuid.UUID      `json:"id"`
	MfaSecret sql.NullString `json:"mfa_secret"`
}

func (q *Queries) EnableMFA(ctx context.Context, arg EnableMFAParams) error {
	_, err := q.db.ExecContext(ctx, enableMFA, arg.ID, arg.MfaSecret)
	return err
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT code, user_id, client_id, redirect_uri, scope, code_challenge, code_challenge_method, expires_at, consumed_at, created_at
FROM oauth_authorization_codes
WHERE code = $1
`

func (q *Queries) GetAuthorizationCode(ctx context.Context, code string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationCode, code)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		pq.Array(&i.Scope),
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT id, user_id, token_hash, token_type, expires_at, used_at, created_at FROM auth_email_tokens
WHERE token_hash = $1 AND token_type = $2 AND expires_at > now() AND used_at IS NULL
`

type GetEmailTokenParams struct {
	TokenHash string `json:"token_hash"`
	TokenType string `json:"token_type"`
}

func (q *Queries) GetEmailToken(ctx context.Context, arg GetEmailTokenParams) (AuthEmailToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailToken, arg.TokenHash, arg.TokenType)
	var i AuthEmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMFAPending = `-- name: GetMFAPending :one
SELECT id, user_id, client_id, redirect_uri, state, scope, code_challenge, code_challenge_method, created_at, expires_at FROM auth_mfa_pending
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetMFAPending(ctx context.Context, id string) (AuthMfaPending, error) {
	row := q.db.QueryRowContext(ctx, getMFAPending, id)
	var i AuthMfaPending
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.State,
		pq.Array(&i.Scope),
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, client_id, client_secret, name, redirect_uris, allowed_scopes, is_confidential, audience, created_at, updated_at
FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.AllowedScopes),
		&i.IsConfidential,
		&i.Audience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthClientByID = `-- name: GetOAuthClientByID :one
SELECT id, client_id, client_secret, name, redirect_uris, allowed_scopes, is_confidential, audience, created_at, updated_at
FROM oauth_clients
WHERE id = $1
`

func (q *Queries) GetOAuthClientByID(ctx context.Context, id uuid.UUID) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClientByID, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.AllowedScopes),
		&i.IsConfidential,
		&i.Audience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT et.id, et.user_id, et.token_hash, et.token_type, et.expires_at, et.used_at, et.created_at, u.id as uid, u.username, u.email, u.password_hash
FROM auth_email_tokens et
JOIN auth_users u ON et.user_id = u.id
WHERE et.token_hash = $1
  AND et.token_type = 'password_reset'
  AND et.expires_at > now()
  AND et.used_at IS NULL
`

type GetPasswordResetTokenByHashRow struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	TokenHash    string       `json:"token_hash"`
	TokenType    string       `json:"token_type"`
	ExpiresAt    time.Time    `json:"expires_at"`
	UsedAt       sql.NullTime `json:"used_at"`
	CreatedAt    time.Time    `json:"created_at"`
	Uid          uuid.UUID    `json:"uid"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
}

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (GetPasswordResetTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByHash, tokenHash)
	var i GetPasswordResetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at
FROM auth_sessions
WHERE id = $1
  AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByAccessToken = `-- name: GetTokenByAccessToken :one
SELECT id, access_token, refresh_token, user_id, client_id, scope, token_type, expires_at, refresh_expires_at, revoked_at, created_at
FROM oauth_tokens
WHERE access_token = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetTokenByAccessToken(ctx context.Context, accessToken sql.NullString) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByAccessToken, accessToken)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.UserID,
		&i.ClientID,
		pq.Array(&i.Scope),
		&i.TokenType,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByRefreshToken = `-- name: GetTokenByRefreshToken :one
SELECT id, access_token, refresh_token, user_id, client_id, scope, token_type, expires_at, refresh_expires_at, revoked_at, created_at
FROM oauth_tokens
WHERE refresh_token = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetTokenByRefreshToken(ctx context.Context, refreshToken sql.NullString) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByRefreshToken, refreshToken)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.UserID,
		&i.ClientID,
		pq.Array(&i.Scope),
		&i.TokenType,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, password_hash, email, is_active, created_at, updated_at, mfa_enabled, mfa_secret, mfa_verified_at, email_verified, email_verified_at
FROM auth_users
WHERE email = $1
  AND is_active = true
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaVerifiedAt,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, email, is_active, created_at, updated_at, mfa_enabled, mfa_secret, mfa_verified_at, email_verified, email_verified_at
FROM auth_users
WHERE id = $1
  AND is_active = true
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaVerifiedAt,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByIDIncludingInactive = `-- name: GetUserByIDIncludingInactive :one
SELECT id, username, password_hash, email, is_active, created_at, updated_at, mfa_enabled, mfa_secret, mfa_verified_at, email_verified, email_verified_at
FROM auth_users
WHERE id = $1
`

func (q *Queries) GetUserByIDIncludingInactive(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDIncludingInactive, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaVerifiedAt,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, email, is_active, created_at, updated_at, mfa_enabled, mfa_secret, mfa_verified_at, email_verified, email_verified_at
FROM auth_users
WHERE username = $1
  AND is_active = true
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaVerifiedAt,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByUsernameIncludingInactive = `-- name: GetUserByUsernameIncludingInactive :one
SELECT id, username, password_hash, email, is_active, created_at, updated_at, mfa_enabled, mfa_secret, mfa_verified_at, email_verified, email_verified_at
FROM auth_users
WHERE username = $1
`

func (q *Queries) GetUserByUsernameIncludingInactive(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameIncludingInactive, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaVerifiedAt,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserMFAStatus = `-- name: GetUserMFAStatus :one

SELECT id, mfa_enabled, mfa_secret FROM auth_users WHERE id = $1
`

type GetUserMFAStatusRow struct {
	ID         uuid.UUID      `json:"id"`
	MfaEnabled bool           `json:"mfa_enabled"`
	MfaSecret  sql.NullString `json:"mfa_secret"`
}

// MFA queries
func (q *Queries) GetUserMFAStatus(ctx context.Context, id uuid.UUID) (GetUserMFAStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getUserMFAStatus, id)
	var i GetUserMFAStatusRow
	err := row.Scan(&i.ID, &i.MfaEnabled, &i.MfaSecret)
	return i, err
}

const insertAuthorizationCode = `-- name: InsertAuthorizationCode :exec
INSERT INTO oauth_authorization_codes (
  code,
  user_id,
  client_id,
  redirect_uri,
  scope,
  code_challenge,
  code_challenge_method,
  expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuthorizationCodeParams struct {
	Code                string         `json:"code"`
	UserID              uuid.UUID      `json:"user_id"`
	ClientID            uuid.UUID      `json:"client_id"`
	RedirectUri         string         `json:"redirect_uri"`
	Scope               []string       `json:"scope"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	ExpiresAt           time.Time      `json:"expires_at"`
}

func (q *Queries) InsertAuthorizationCode(ctx context.Context, arg InsertAuthorizationCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthorizationCode,
		arg.Code,
		arg.UserID,
		arg.ClientID,
		arg.RedirectUri,
		pq.Array(arg.Scope),
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO oauth_tokens (
  access_token,
  refresh_token,
  user_id,
  client_id,
  scope,
  token_type,
  expires_at,
  refresh_expires_at
)
VALUES ($1, $2, $3, $4, $5, COALESCE($8::text, 'bearer'), $6, $7)
RETURNING id, access_token, refresh_token, user_id, client_id, scope, token_type, expires_at, refresh_expires_at, revoked_at, created_at
`

type InsertTokenParams struct {
	AccessToken      sql.NullString `json:"access_token"`
	RefreshToken     sql.NullString `json:"refresh_token"`
	UserID           uuid.NullUUID  `json:"user_id"`
	ClientID         uuid.UUID      `json:"client_id"`
	Scope            []string       `json:"scope"`
	ExpiresAt        time.Time      `json:"expires_at"`
	RefreshExpiresAt sql.NullTime   `json:"refresh_expires_at"`
	TokenType        sql.NullString `json:"token_type"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, insertToken,
		arg.AccessToken,
		arg.RefreshToken,
		arg.UserID,
		arg.ClientID,
		pq.Array(arg.Scope),
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.TokenType,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.UserID,
		&i.ClientID,
		pq.Array(&i.Scope),
		&i.TokenType,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, client_id, client_secret, name, redirect_uris, allowed_scopes, is_confidential, audience, created_at, updated_at
FROM oauth_clients
ORDER BY created_at DESC
`

func (q *Queries) ListOAuthClients(ctx context.Context) ([]OauthClient, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClient
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Name,
			pq.Array(&i.RedirectUris),
			pq.Array(&i.AllowedScopes),
			&i.IsConfidential,
			&i.Audience,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE auth_email_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEmailTokenUsed, id)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE auth_email_tokens
SET used_at = now()
WHERE token_hash = $1 AND token_type = 'password_reset'
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, tokenHash)
	return err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE auth_users
SET is_active = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, reactivateUser, id)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE oauth_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeTokenByAccessToken = `-- name: RevokeTokenByAccessToken :exec
UPDATE oauth_tokens
SET revoked_at = now()
WHERE access_token = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeTokenByAccessToken(ctx context.Context, accessToken sql.NullString) error {
	_, err := q.db.ExecContext(ctx, revokeTokenByAccessToken, accessToken)
	return err
}

const revokeTokenByRefreshToken = `-- name: RevokeTokenByRefreshToken :exec
UPDATE oauth_tokens
SET revoked_at = now()
WHERE refresh_token = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeTokenByRefreshToken(ctx context.Context, refreshToken sql.NullString) error {
	_, err := q.db.ExecContext(ctx, revokeTokenByRefreshToken, refreshToken)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec

UPDATE auth_users
SET email_verified = true, email_verified_at = now(), updated_at = now()
WHERE id = $1
`

// Email verification queries
func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setEmailVerified, id)
	return err
}

const updateOAuthClient = `-- name: UpdateOAuthClient :one
UPDATE oauth_clients
SET
  name = COALESCE(NULLIF($1::text, ''), name),
  redirect_uris = COALESCE($2::text[], redirect_uris),
  allowed_scopes = COALESCE($3::text[], allowed_scopes),
  is_confidential = COALESCE($4, is_confidential),
  audience = COALESCE(NULLIF($5::text, ''), audience),
  updated_at = now()
WHERE client_id = $6
RETURNING id, client_id, client_secret, name, redirect_uris, allowed_scopes, is_confidential, audience, created_at, updated_at
`

type UpdateOAuthClientParams struct {
	Name           sql.NullString `json:"name"`
	RedirectUris   []string       `json:"redirect_uris"`
	AllowedScopes  []string       `json:"allowed_scopes"`
	IsConfidential sql.NullBool   `json:"is_confidential"`
	Audience       sql.NullString `json:"audience"`
	ClientID       string         `json:"client_id"`
}

func (q *Queries) UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, updateOAuthClient,
		arg.Name,
		pq.Array(arg.RedirectUris),
		pq.Array(arg.AllowedScopes),
		arg.IsConfidential,
		arg.Audience,
		arg.ClientID,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.AllowedScopes),
		&i.IsConfidential,
		&i.Audience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE auth_users
SET email = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth_users
SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserUsername = `-- name: UpdateUserUsername :exec
UPDATE auth_users
SET username = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserUsernameParams struct {
	Username string    `json:"username"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserUsername, arg.Username, arg.ID)
	return err
}
