// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthEmailToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	TokenType string       `json:"token_type"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type AuthMfaPending struct {
	ID                  string         `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	ClientID            sql.NullString `json:"client_id"`
	RedirectUri         sql.NullString `json:"redirect_uri"`
	State               sql.NullString `json:"state"`
	Scope               []string       `json:"scope"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	CreatedAt           time.Time      `json:"created_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
}

type AuthSession struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type AuthUser struct {
	ID                uuid.UUID      `json:"id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	Email             string         `json:"email"`
	IsActive          bool           `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	MfaEnabled        bool           `json:"mfa_enabled"`
	MfaSecret         sql.NullString `json:"mfa_secret"`
	MfaVerifiedAt     sql.NullTime   `json:"mfa_verified_at"`
	EmailVerified     bool           `json:"email_verified"`
	EmailVerifiedAt   sql.NullTime   `json:"email_verified_at"`
	LastLoginAt       sql.NullTime   `json:"last_login_at"`
	PasswordChangedAt sql.NullTime   `json:"password_changed_at"`
	GivenName         sql.NullString `json:"given_name"`
	FamilyName        sql.NullString `json:"family_name"`
	Picture           sql.NullString `json:"picture"`
}

type OauthAuthorizationCode struct {
	Code                string         `json:"code"`
	UserID              uuid.UUID      `json:"user_id"`
	ClientID            uuid.UUID      `json:"client_id"`
	RedirectUri         string         `json:"redirect_uri"`
	Scope               []string       `json:"scope"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	ExpiresAt           time.Time      `json:"expires_at"`
	ConsumedAt          sql.NullTime   `json:"consumed_at"`
	CreatedAt           time.Time      `json:"created_at"`
}

type OauthClient struct {
	ID             uuid.UUID      `json:"id"`
	ClientID       string         `json:"client_id"`
	ClientSecret   sql.NullString `json:"client_secret"`
	Name           string         `json:"name"`
	RedirectUris   []string       `json:"redirect_uris"`
	AllowedScopes  []string       `json:"allowed_scopes"`
	IsConfidential bool           `json:"is_confidential"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Audience       string         `json:"audience"`
}

type OauthToken struct {
	ID               uuid.UUID      `json:"id"`
	AccessToken      sql.NullString `json:"access_token"`
	RefreshToken     sql.NullString `json:"refresh_token"`
	UserID           uuid.NullUUID  `json:"user_id"`
	ClientID         uuid.UUID      `json:"client_id"`
	Scope            []string       `json:"scope"`
	TokenType        string         `json:"token_type"`
	ExpiresAt        time.Time      `json:"expires_at"`
	RefreshExpiresAt sql.NullTime   `json:"refresh_expires_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}
